Dacia spring charging
node-red-contrib/node-red-contrib-renault-ze pull request #73
Opened 2022-07-12 12:32 UTC by JLorenz86

I added the function "setChargePause". This function is neccessary for stop and start charging the Dacia Spring.

2022-07-12 12:32 UTC, CLAassistant commented
[![CLA assistant check](https://cla-assistant.io/pull/badge/not_signed)](https://cla-assistant.io/node-red-contrib/node-red-contrib-renault-ze?pullRequest=73) <br/>Thank you for your submission! We really appreciate it. Like many open source projects, we ask that you sign our [Contributor License Agreement](https://cla-assistant.io/node-red-contrib/node-red-contrib-renault-ze?pullRequest=73) before we can accept your contribution.<br/><sub>You have signed the CLA already but the status is still pending? Let us [recheck](https://cla-assistant.io/check/node-red-contrib/node-red-contrib-renault-ze?pullRequest=73) it.</sub>

2022-07-14 13:16 UTC, konne requested changes

2022-07-14 13:16 UTC, konne commented on src/ZEServices.ts
> +                    "action": action ? "pause" : "resume"
```suggestion
        const data: DataContainer<any> =
        {
            "data":
            {
                "type": "ChargePauseResume",
                "attributes":
                {
                    "action": pause ? "pause" : "resume"
```

2022-07-14 13:16 UTC, konne commented on src/ZEServices.ts
> +                    "action": action ? "pause" : "resume"
@JLorenz86 please adapt the current code. It does not compile and I also made a small codesmell fix

2022-07-14 13:16 UTC, konne commented
@JLorenz86 I now also enabled CI checks for you so you can see if the compile steps get green.

2022-07-16 12:12 UTC, JLorenz86 commented
Now, it should work.

2022-07-16 16:02 UTC, JLorenz86 commented
I have discovered another error in my version: The function for the Dacia spring requires a different base URL. I will add it this evening.

2022-07-16 17:48 UTC, JLorenz86 commented
I will fix the failures in my code and reopen an new pull request after that.

2022-07-16 17:48 UTC, closed without merging